export const SAVE_GIPHY_RESPONSE = "SAVE_GIPHY_RESPONSE";
export const SAVE_TRENDING_GIFS = "SAVE_TRENDING_GIFS";
export const MARK_AS_FAVORITE = "MARK_AS_FAVORITE";
export const SET_LOADING_STATE = "SET_LOADING_STATE";
export const UNMARK_AS_FAVORITE = "UNMARK_AS_FAVORITE";
